services:
  client:
    build:
      context: .
      dockerfile: client/docker/Dockerfile.client
      target: dev-client
    image: client
    ports:
      - "3000:3000"

  server:
    build:
      context: .
      dockerfile: server/docker/Dockerfile.server
      target: dev-server
    image: server
    ports:
      - "8080:8080"
