services:
      build-backend:
        build:
          context: ./
          dockerfile: ./server/Dockerfile
      build-frontend:
        build:
          context: ./
          dockerfile: ./client/Dockerfile