services:
  base:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: build-base
  client:
    depends_on:
      - base
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    image: build-client
  server:
    depends_on:
      - base
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    image: build-server
