version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
        version: 19.03.13
        # docker_layer_caching: true

      # build and push Docker image
      - run: |
        TAG=0.1.$CIRCLE_BUILD_NUM
        docker build -f server/docker/Dockerfile.server \
                     --target test-server \
                     -t circleci-public/circleci-demo-docker:$TAG .

      - run: |
        docker run circleci-public/circleci-demo-docker:$TAG

      - store_test_results:
        path: ./reports/junit/
      - store_artifacts:
        path: ./reports/junit
