jobs:
  install:
    docker:
      - image: circleci/node

    steps:
      - checkout
      - run: yarn install

  test-backend:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn workspace server test-ci

      - store_test_results:
          path: ./reports/
      - store_artifacts:
          path: ./reports/

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - test-backend:
        requires:
          - install
