version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          # docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -f server/docker/Dockerfile.server-prod \
                       --target test-server \
                       -t circleci-public/circleci-demo-docker:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push circleCI-public/circleci-demo-docker:$TAG
